# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  erosion_config = debug

else ifeq ($(config),release)
  erosion_config = release

else ifeq ($(config),dist)
  erosion_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := erosion

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

erosion:
ifneq (,$(erosion_config))
	@echo "==== Building erosion ($(erosion_config)) ===="
	@${MAKE} --no-print-directory -C . -f erosion.make config=$(erosion_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f erosion.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   erosion"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"